{% set name = "fluent-logger" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7a34a30caec7828b3dfc304360cae0557aa8bb550106e613bab857a02c4cc8a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - msgpack-python

test:
  imports:
    - fluent

about:
  home: http://fluentd.org
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A structured logger for Fluentd (Python)

  doc_url: https://docs.fluentd.org/language-bindings/python
  dev_url: https://github.com/fluent/fluent-logger-python

extra:
  recipe-maintainers:
    - andrew-mcgrath
    - pierrsc
