travis:
  secure:
    BINSTAR_TOKEN: KYC4sTfF+AdGTHGnNu6ycYPOZwvyOl1L6wQPMi1moiNCArmCakx+1kBhe4bdG8D/9TDZYZ3ktfniLqx4NxLol17uz90OZ582K3/0vvmKOprMluMONFwRCDEeldsxSp8gZCcxLwXF89DGF0QyNf/cntjoL7z3vbN82m7UwnenQPh2VOzErUZl96cIRfqZxC/IjaH6TAIFDxXsBT1Sn6REoVdk+cRIakmDBJNkOE7Ex8yqNYwH48bbeHQCwWbKZcY810w2SkpR54MVayRJunwezJV33ARopxDIfIM7OsrzZCINaLL7tbHlnRTX61klr3drNL+4fSNLo4mlzi62OaM2eMYDSFBMC38+jx/Rp422eqN4B8g2hgAgQ1bVaIVDInqRh6NzjQmACNJsKj6LiWQka3FN28XbdsObT/ZXyPE8Epdjg/SHjpVofDN2/avaqx5SKILi6oC38cS0V0TKsSrKsu6KI1wKAsWNz6AftO7FY9lPbqJWNgGvEVYzIAcvkvS1Av0sj5aimbdYt23UU65jzZRJ2X7KoxYnlKiL9RhBd/3XomFM7XdkWl9azgoevglIhF4mMaTHcsH/oO44ajpdVlkuiqytK/JzjwGDtyPGgiNPtscKeEOKfO41U8GeBTx7GIyksbKAUtvplA+qaUXgfqNptw1hHX7N+pfJIHqJTsw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
